env:
  es6: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 8
  sourceType: module
globals:
  Sphere: true
  Color: true
  DirectoryStream: true
  Dispatch: true
  FS: true
  FileOp: true
  FileStream: true
  Font: true
  IndexList: true
  Joystick: true
  Key: true
  Keyboard: true
  Mixer: true
  Model: true
  Mouse: true
  MouseKey: true
  RNG: true
  SSj: true
  Sample: true
  Server: true
  Shader: true
  Shape: true
  ShapeType: true
  Socket: true
  Sound: true
  SoundStream: true
  Surface: true
  TextDecoder: true
  TextEncoder: true
  Texture: true
  Transform: true
  VertexList: true
rules:
  array-bracket-spacing:
    - error
    - always
  comma-spacing: error
  func-style:
    - error
    - declaration
    - {
        allowArrowFunctions: true
      }
  indent:
    - error
    - tab
    - {
        SwitchCase: 1
      }
  no-await-in-loop: warn
  no-floating-decimal: error
  no-implicit-coercion: error
  no-invalid-this: error
  no-lone-blocks: error
  object-curly-spacing:
    - error
    - always
  semi:
    - error
    - always
