env:
  es6: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 8
  sourceType: module
globals:
  global: true
  console: true
  require: true
  Sphere: true
  Color: true
  DirectoryStream: true
  Dispatch: true
  FS: true
  FileOp: true
  FileStream: true
  Font: true
  IndexList: true
  Joystick: true
  Key: true
  Keyboard: true
  Mixer: true
  Model: true
  Mouse: true
  MouseKey: true
  RNG: true
  SSj: true
  Sample: true
  Server: true
  Shader: true
  Shape: true
  ShapeType: true
  Socket: true
  Sound: true
  SoundStream: true
  Surface: true
  TextDecoder: true
  TextEncoder: true
  Texture: true
  Transform: true
  VertexList: true
rules:
  array-bracket-spacing:
    - error
    - always
  comma-dangle:
    - error
    - always-multiline
  comma-spacing: error
  complexity:
    - warn
  curly:
    - error
    - multi-or-nest
    - consistent
  func-style:
    - error
    - declaration
    - {
        allowArrowFunctions: true,
      }
  indent:
    - error
    - tab
    - {
        SwitchCase: 1,
        flatTernaryExpressions: true,
      }
  no-console: off
  no-debugger: error
  no-floating-decimal: error
  no-implicit-coercion: error
  no-invalid-this: error
  no-lone-blocks: error
  no-trailing-spaces: error
  no-restricted-syntax:
    - error
    - BinaryExpression[operator='==']
    - BinaryExpression[operator='!=']
    - ForInStatement
  no-unused-expressions: error
  no-unused-vars: warn
  object-curly-spacing:
    - error
    - always
  require-await: warn
  semi:
    - error
    - always
  space-infix-ops: error
